name: Production CI

on:
  push:
    branches:
      - Production
  pull_request:
    branches:
      - Production

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'EcommercePlatform.sln'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --no-restore --configuration Release 