name: Production CI

on:
  push:
    branches:
      - Production
  pull_request:
    branches:
      - Production

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'EcommercePlatform.sln'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      # SQL Server service container
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "YourStrong@Password1"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Password1" -Q "SELECT 1" || exit 1
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # Redis service container
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --no-restore --configuration Release

    - name: Test
      run: dotnet test ${{ env.SOLUTION_FILE }} --no-build --verbosity normal --configuration Release

    - name: Check for build warnings
      run: |
        $buildOutput = dotnet build ${{ env.SOLUTION_FILE }} --configuration Release
        if ($buildOutput -match "warning") {
          Write-Host "##[warning]Build contains warnings"
          exit 1
        }

    - name: Verify Docker Compose
      run: |
        docker-compose config

    - name: Check for outdated packages
      run: |
        dotnet list ${{ env.SOLUTION_FILE }} package --outdated

    - name: Build status
      if: always()
      run: |
        if ($env:JOB_STATUS -eq 'success') {
          echo "##[section]Build Status: ✅ Success"
          echo "All checks passed successfully!"
        } else {
          echo "##[error]Build Status: ❌ Failed"
          echo "Please check the build logs for details."
        }
      env:
        JOB_STATUS: ${{ job.status }} 