name: Production CI

on:
  push:
    branches:
      - Production
  pull_request:
    branches:
      - Production

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: 'EcommercePlatform.sln'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --no-restore --configuration Release

    - name: Check for build warnings
      run: |
        $buildOutput = dotnet build ${{ env.SOLUTION_FILE }} --configuration Release
        if ($buildOutput -match "warning") {
          Write-Host "##[warning]Build contains warnings"
          exit 1
        }

    - name: Verify Docker Compose
      run: |
        docker-compose config

    - name: Check for outdated packages
      run: |
        dotnet list ${{ env.SOLUTION_FILE }} package --outdated

    - name: Build status
      if: always()
      run: |
        if ($env:JOB_STATUS -eq 'success') {
          echo "##[section]Build Status: ✅ Success"
          echo "All checks passed successfully!"
        } else {
          echo "##[error]Build Status: ❌ Failed"
          echo "Please check the build logs for details."
        }
      env:
        JOB_STATUS: ${{ job.status }} 